package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class App implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   private java.lang.String identifier;

   public App()
   {
   }

   public java.lang.String getIdentifier()
   {
      return this.identifier;
   }

   public void setIdentifier(java.lang.String identifier)
   {
      this.identifier = identifier;
   }

   @Override
   public String toString() {
      return "App [identifier=" + identifier + "]";
   }
}