package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Merchant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String api_key;

   public Merchant()
   {
   }

   private String id;

   private String name;

   private double totalExposureAmount;

   public String getId()
   {
      return id;
   }

   public void setId(String id)
   {
      this.id = id;
   }

   public String getName()
   {
      return name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public double getTotalExposureAmount()
   {
      return totalExposureAmount;
   }

   public void setTotalExposureAmount(double totalExposureAmount)
   {
      this.totalExposureAmount = totalExposureAmount;
   }

   public java.lang.String getApi_key()
   {
      return this.api_key;
   }

   public void setApi_key(java.lang.String api_key)
   {
      this.api_key = api_key;
   }

   @Override
   public String toString()
   {
      return "Merchant [id=" + id + ", name=" + name + ", api_key =" + api_key + "]";
   }

}