package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Mobile implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String device_id;

   public Mobile()
   {
   }

   public java.lang.String getDevice_id()
   {
      return this.device_id;
   }

   public void setDevice_id(java.lang.String device_id)
   {
      this.device_id = device_id;
   }

   @Override
   public String toString() {
      return "Mobile [device_id=" + device_id + "]";
   }
}