package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaySenseTransaction implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PaySenseTransaction() {
    }

}