package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaySenseTransaction implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.paysense.entity.Merchant merchant;
   private com.paysense.entity.App app;
   private com.paysense.entity.Mobile mobile;
   private com.paysense.entity.Transaction transaction;
   private java.lang.String datetime;

   public PaySenseTransaction()
   {
   }

   public com.paysense.entity.Merchant getMerchant()
   {
      return this.merchant;
   }

   public void setMerchant(com.paysense.entity.Merchant merchant)
   {
      this.merchant = merchant;
   }

   public com.paysense.entity.App getApp()
   {
      return this.app;
   }

   public void setApp(com.paysense.entity.App app)
   {
      this.app = app;
   }

   public com.paysense.entity.Mobile getMobile()
   {
      return this.mobile;
   }

   public void setMobile(com.paysense.entity.Mobile mobile)
   {
      this.mobile = mobile;
   }

   public com.paysense.entity.Transaction getTransaction()
   {
      return this.transaction;
   }

   public void setTransaction(com.paysense.entity.Transaction transaction)
   {
      this.transaction = transaction;
   }

   public java.lang.String getDatetime()
   {
      return this.datetime;
   }

   public void setDatetime(java.lang.String datetime)
   {
      this.datetime = datetime;
   }
   @Override
   public String toString() {
      return "PaySenseTransaction [merchant=" + merchant + ", app=" + app + ", mobile="   + mobile + ", transaction=" + transaction + ", datetime=" + datetime + "]";
   }
}