package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TransactionStatus implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   static TransactionStatus INIT = new TransactionStatus("INIT");
   static TransactionStatus ELIGIBLE = new TransactionStatus("ELIGIBLE");
   static TransactionStatus REVIEW = new TransactionStatus("REIVEW");
   static TransactionStatus REJECT = new TransactionStatus("REJECT");

   private java.lang.String name;

   public TransactionStatus(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getName()
   {
      return this.name;
   }
}