package com.paysense.entity;

import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TranObjectContainer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TranObjectContainer() {
    }

	private Transaction newTransaction;
	private List<Transaction> oldTransactions;
	
	public Transaction getNewTransaction() {
		return newTransaction;
	}
	public void setNewTransaction(Transaction newTransaction) {
		this.newTransaction = newTransaction;
	}
	public List<Transaction> getOldTransactions() {
		return oldTransactions;
	}
	public void setOldTransactions(List<Transaction> oldTransactions) {
		this.oldTransactions = oldTransactions;
	}
}