package com.paysense.entity;

import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TranObjectContainer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TranObjectContainer() {
    }
	private User user;
	private Transaction newTransaction;
	private List<Transaction> oldTransactions;
	private List<WhiteListObject> whiteList;
	
	public Transaction getNewTransaction() {
		return newTransaction;
	}
	public void setNewTransaction(Transaction newTransaction) {
		this.newTransaction = newTransaction;
	}
	public List<Transaction> getOldTransactions() {
		return oldTransactions;
	}
	public void setOldTransactions(List<Transaction> oldTransactions) {
		this.oldTransactions = oldTransactions;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user){
		this.user = user;
	}
	public List<WhiteListObject> getWhiteList(){
		return whiteList;
	}
	public void setWhiteList(List<WhiteListObject> whiteList){
		this.whiteList = whiteList;
	}
}