package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String phone;

   private String id;

   private double totalSpend;

   private int numOfGoodTrans;

   public User() {
   }

   public String getId()
   {
      return id;
   }

   public void setId(String id)
   {
      this.id = id;
   }

   public double getTotalSpend()
   {
      return totalSpend;
   }

   public void setTotalSpend(double totalSpend)
   {
      this.totalSpend = totalSpend;
   }

   public int getNumOfGoodTrans()
   {
      return numOfGoodTrans;
   }

   public void setNumOfGoodTrans(int numOfGoodTrans)
   {
      this.numOfGoodTrans = numOfGoodTrans;
   }

   public String getPhone()
   {
      return this.phone;
   }

   public void setPhone(String phone)
   {
      this.phone = phone;
   }

   @Override
   public String toString()
   {
      return "User [id=" + id + ", totalSpend=" + totalSpend + ", numOfGoodTrans=" + numOfGoodTrans + "]";
   }

}