package com.paysense.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WhiteListObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String type;
   private java.lang.String value;

   public WhiteListObject()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

	@Override
	public String toString() {
		return "WhiteListObject [type=" + type + ", value=" + value + "]";
	}
}