package com.paysense.entity;

rule "Extract New Transaction"
	when
		TranObjectContainer(newTransaction.status == 0, $tran:newTransaction)
	then
		insert($tran);
end

rule "Usage Eligible"
    when	
        $tran : Transaction(user.numOfGoodTrans > 3 && user.totalSpend > 1000)
    then
        System.out.println( "inside Usage Eligible rule: "+$tran );
  
        $tran.setStatus(1);
        
end

rule "Usage Review"
    when
        $tran : Transaction( status == 0 && (user.numOfGoodTrans <= 3 || user.totalSpend <= 1000))  
    then
        System.out.println( "inside Usage Review rule: "+$tran );
  
        $tran.setStatus(17);
end
