package com.paysense.entity;

rule "Extract New Transaction"
	when
		TranObjectContainer(newTransaction.status == 0, $tran:newTransaction, $user:user)
	then
		insert($tran);
		insert($user);
end

rule "Usage Eligible"
    when	
	$tran : Transaction(status == 0)
        $user : User(id==$tran.userId && numOfGoodTrans > 3 && totalSpend > 1000)
    then
        System.out.println( "inside Usage Eligible rule: "+$tran );
  
        $tran.setStatus(1);
        
end

rule "Usage Review"
    when
	$tran : Transaction(status == 0)
        $user : User(id==$tran.userId && (numOfGoodTrans <= 3 || totalSpend <= 1000))
    then
        System.out.println( "inside Usage Review rule: "+$tran );
  
        $tran.setStatus(2);
end