package com.paysense.rules;

import java.util.List;
import java.util.ArrayList;

import com.paysense.entity.Transaction;
import com.paysense.entity.TranObjectContainer;

rule "Velocity Eligible"
    when
        TranObjectContainer(newTransaction.status == 0, $tran:newTransaction, $oldTrans:oldTransactions)
        $goodTrans: ArrayList(size>5) from collect (Transaction(status == 1) from $oldTrans) 
    then
        System.out.println( "******inside Velocity Eligible rule - old transactions size: "+$goodTrans.size());
        $tran.setStatus(1);       
end