package com.paysense.entity;

rule "White List Rule"
	when
		TranObjectContainer(newTransaction.status == 0, $tran:newTransaction, $user:user,$whiteList:whiteList )
		WhiteListObject((type=="CUSTOMER" && value==$user.id) || (type=="PHONE" && value==$user.phone)) from $whiteList
	then
		System.out.println( "**************testing**************: "+$user );
		System.out.println( "**************whiteList**************: "+ $whiteList);
		$tran.setStatus(1);
end